pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - "status-success=codecov/project/backend"
      - "status-success=codecov/project/frontend"
      - "status-success=ci/circleci: client"
      - "status-success=ci/circleci: server"
    actions:
      merge:
        method: merge
